# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v0.1.10
_src_path: https://github.com/run-llama/template-workflow-data-extraction
project_name: extraction-review-tmp5-classify-sec
project_title: Extraction Review Tmp5 Classify Sec
