/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * List of events reported in the 8-K filing
 */
export type Events = Event8K[] | null;
/**
 * Category of the event (e.g., Item 1.01, Item 2.02)
 */
export type Category = string | null;
/**
 * Description of the event reported in the 8-K
 */
export type Description = string | null;

export interface Form8KData {
  events?: Events;
}
export interface Event8K {
  category?: Category;
  description?: Description;
}
