/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Revenue for the quarter
 */
export type QuarterlyRevenue = string | null;
/**
 * Net income for the quarter
 */
export type QuarterlyNetIncome = string | null;
/**
 * Total assets at the end of the quarter
 */
export type TotalAssets = string | null;
/**
 * Total liabilities at the end of the quarter
 */
export type TotalLiabilities = string | null;

export interface Form10QData {
  quarterly_revenue?: QuarterlyRevenue;
  quarterly_net_income?: QuarterlyNetIncome;
  total_assets?: TotalAssets;
  total_liabilities?: TotalLiabilities;
}
