/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Total revenue for the fiscal year
 */
export type TotalRevenue = string | null;
/**
 * Net income for the fiscal year
 */
export type NetIncome = string | null;
/**
 * Total assets at the end of the fiscal year
 */
export type TotalAssets = string | null;
/**
 * Total liabilities at the end of the fiscal year
 */
export type TotalLiabilities = string | null;

export interface Form10KData {
  total_revenue?: TotalRevenue;
  net_income?: NetIncome;
  total_assets?: TotalAssets;
  total_liabilities?: TotalLiabilities;
}
